### ISSUE TITLE
Problem with Winston ?

### ISSUE THREAD

**Issue by DegiSeb** [empierre/domoticz_linky#19]
Hi,

I've some troubles to get the script working.
Indeed, I correctly receive data from Enedis because I can see them into the differents export_* files. However nothing appears in the dummy device in Domoticz, and I get this error when I run ./domoticz_linky.sh

```
/home/pi/domoticz/plugins/domoticz_linky/node_modules/winston/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/home/pi/domoticz/plugins/domoticz_linky/node_modules/winston/node_modules/winston-transport/legacy.js:18:11)
    at DerivedLogger.add (/home/pi/domoticz/plugins/domoticz_linky/node_modules/winston/lib/winston/logger.js:270:9)
    at Object.winston.(anonymous function).args [as add] (/home/pi/domoticz/plugins/domoticz_linky/node_modules/winston/lib/winston.js:101:55)
    at Object.<anonymous> (/home/pi/domoticz/plugins/domoticz_linky/domoticz_linky.js:205:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```

Do you think it could be the new version of Winston that is not fit for the script ? 

Thanks

**Comment by singinglarvae** [comment]
Hi,

Same issue here using the very last domoticz version (V4.9700, Build Date: 2018-06-23 16:24:51), an updated version of Raspbian on a Pi 3. The export_* files are indeed filled with values, but the script ends on the very same error:
`
pi@marc-domoticz:~/domoticz/plugins/domoticz_linky $ ./domoticz_linky.sh
/home/pi/domoticz/plugins/domoticz_linky/node_modules/winston/node_modules/winston-transport/legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.
    at new LegacyTransportStream (/home/pi/domoticz/plugins/domoticz_linky/node_modules/winston/node_modules/winston-transport/legacy.js:18:11)
    at DerivedLogger.add (/home/pi/domoticz/plugins/domoticz_linky/node_modules/winston/lib/winston/logger.js:270:9)
    at Object.winston.(anonymous function).args [as add] (/home/pi/domoticz/plugins/domoticz_linky/node_modules/winston/lib/winston.js:101:55)
    at Object.<anonymous> (/home/pi/domoticz/plugins/domoticz_linky/domoticz_linky.js:205:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
`

**Comment by flecoufle** [comment]
I have the same issue, I downgrade winston (example to 2.2.0) and it works better
$ cat package.json 
{
  "_from": "winston@2.2.0",
  "_id": "winston@2.2.0",
  "_inBundle": false,
  "_integrity": "sha1-LIU92Hq1UqjoSF1yy7+aIobwKbc="

**Comment by empierre** [comment]
Yes, tested in 2.4.2 works fine
